### ISSUE TITLE
"Library Artists" view currently displays error

### ISSUE THREAD

**Issue by igor-makarov** [antrancs/maeve#11]
The error is "something went wrong" and it's due to `getArtistArtwork` returning 400.

This doesn't affect playback capability but there is no artist photos displayed.

**Comment by igor-makarov** [comment]
No, I'm using the website. I meant this page: https://maevemusic.app/me/library/artists

**Comment by antrancs** [comment]
Ah, I see. Library artists don't have an artwork though. I was using a placeholder image for them. But I made some changes yesterday which caused this error. Will fix it later today.

Thanks.

**Comment by igor-makarov** [comment]
By the way, in AM artists have photos. Don't know if this is available in the API, but it's the round image in the page header as shown here: https://itunes.apple.com/us/artist/arctic-monkeys/62820413

**Comment by antrancs** [comment]
Artist artworks don't get officially supported through the API. I had to do some workaround to get one to display in the artist detail page you see here: https://maevemusic.app/artists/159260351

It's the same for artists in your library. But let me check again if I can do the same workaround for library artists.

**Comment by antrancs** [comment]
This should be fixed now. And the API for library artists only returns their name, so I just use a placeholder image there. Hopefully it will change in the future.

**Comment by igor-makarov** [comment]
Yeah, I checked other web apps and they don't have it either.

Perhaps open a radar?

**Comment by antrancs** [comment]
I'm thinking about getting it from Genius 😅. I'll get to it later when time permits.

**Comment by igor-makarov** [comment]
Very nice! 💪
