### ISSUE TITLE
Play button not working after that was suspended

### ISSUE THREAD

**Issue by freddydumont** [antrancs/maeve#14]
First, congrats on making such a nice app. It's way better than iTunes.

Here's my issue:

Firefox automatically suspends unused tabs to free up space, so if I press pause, Maeve will be suspended at some point. When I go back, the play button doesn't do anything. It remembers what song I was playing and the position I was at, but nothing happens, expect the UI change from play/pause icons.

I have to refresh the app, and lose my "progression" in the playlist.

**Comment by antrancs** [comment]
Thanks. Regarding the issue, I think the best workaround is to persist the play queue and your current song so when you refresh the page you still can resume your listening, which is suggested by this #15

**Comment by antrancs** [comment]
Did a workaround for it in the new build
