### ISSUE TITLE
Implement right click context menu for songs and albums

### ISSUE THREAD

**Issue by pedrogarcia** [antrancs/maeve#18]
The ... options has a very small tap target, and requires a longe mouse movement to activate it. 
Much better would be to allow these same options to be accessed by right clicking a song, to open the context menu.

**Comment by antrancs** [comment]
Hi, thanks for this nice suggestion. This is a quick fix which I have done in the new commit.
Regarding the other 2 suggestions, they require a bit more implementation, so I will work on them later. 😀

I'm working on the PWA feature for Maeve at the moment. 🙂
