### ISSUE TITLE
Top artist's music 

### ISSUE THREAD

**Issue by robsonsnjr** [antrancs/maeve#28]
Implement a "top music" row on artist's page.
Or maybe only a "star" next to the songs, like on itunes (although I think the first suggestion does not invalidate the second one).
It is make sense?

**Comment by antrancs** [comment]
Hi, I just added the Top Songs & Latest Release sections to the Artist page. Please check it out and let me know if that's okay.

Regarding the.star next to a song, I'm not sure I can replicate that with the support of the current Apple Music API. So for now, I just added new sections to the Artist page.

**Comment by robsonsnjr** [comment]
I can't see a "Latest releases" section. It is ordered by release date on "albums" section?
The artist page seems ok for me.
Thanks for the super fast implementation! :)

**Comment by antrancs** [comment]
Not all artists has a latest release. It's at the top of the Artist page, like this:

<img width="1421" alt="screen shot 2019-02-10 at 9 42 26 am" src="https://user-images.githubusercontent.com/14043840/52528766-76f8e980-2d18-11e9-86a7-306846616523.png">

https://maevemusic.app/artists/632781795
https://maevemusic.app/artists/956078923

**Comment by robsonsnjr** [comment]
Ok. Thanks!
