### ISSUE TITLE
Keyboard Controls

### ISSUE THREAD

**Issue by jayatflight** [antrancs/maeve#31]
It would be fantastic if we could use the keyboard to control playback! Like having space play/pause and the arrow keys skip, or using the YouTube controls! It would also let use extensions to use media keys, and that would be useful too!
Thanks!

**Comment by antrancs** [comment]
Hey, I just implemented it. For now, the keyboard shortcuts are:

**Space**: Play/Pause
**Ctrl (Cmd) - Right**: Next track
**Ctrl (Cmd) - Left**: Previous track
**Ctrl (Cmd) - Down**: Turn down volume
**Ctrl (Cmd) - Up**: Turn up volume
**Ctrl (Cmd) + Shift + Up**: Max volume
**Ctrl (Cmd) + Shift + Down**: Mute

Let me know it it works fine for you as well.
