### ISSUE TITLE
When Now Playing pane is active, keyboard is hijacked

### ISSUE THREAD

**Issue by igor-makarov** [antrancs/maeve#39]
Could be related to #31 being done.

Steps to reproduce: 

1. Play a song.
2. Try to use the search bar.

Expected:  
Text entry 

Actual:  
No text entry, only spacebar controls playback.

**Comment by antrancs** [comment]
Ah, my bad. Thanks for reporting this. Will make a fix later today :smiley:

**Comment by igor-makarov** [comment]
Awesome, thanks! 💪

**Comment by antrancs** [comment]
Hey, I just made a fix for that. Let me know if it's working ok for you as well 😃

**Comment by igor-makarov** [comment]
Hmm, the keyboard working well when in the search bar. 

However it still hijacks all the keys, such as Ctrl-R and Alt-F4 when not in the search bar.

**Comment by antrancs** [comment]
Oops, sorry. The new version should be working fine now 😅

**Comment by igor-makarov** [comment]
Yeah, looks okay now! Thanks!
💪
