### ISSUE TITLE
When Adding description to play list Spacebar pauses music instead of inserting a space 

### ISSUE THREAD

**Issue by infurno** [antrancs/maeve#41]
I found that when adding a description to a Playlist, any time you try to put a space in the descriptions it will pause the play out side of the edit Modal.

**Comment by antrancs** [comment]
Thanks, I just made a fix for that. Will be available in the next build tomorrow. Will let you know when the new build is live :)

**Comment by antrancs** [comment]
Hi, the issue should be resolved in the new build.
