### ISSUE TITLE
Artist albums or songs not showing up in 'Artist' tab

### ISSUE THREAD

**Issue by mattharo** [antrancs/maeve#43]
In the artist tab, when you click on the artist no albums or songs appear.
![Screenshot 2019-04-25 at 11 35 31 AM](https://user-images.githubusercontent.com/48073208/56748769-67514480-674e-11e9-919b-444fe1279eb9.png)

**Comment by antrancs** [comment]
Looks like an Apple Music API bug. The relationships (albums/playlists) are not returned for library artists.

<img width="415" alt="Screen Shot 2019-04-26 at 3 39 48 PM" src="https://user-images.githubusercontent.com/14043840/56811800-e2435980-6839-11e9-947d-32bc7734a3cd.png">

I'll submit a bug ticket to Apple.
Thanks for reporting this.

**Comment by antrancs** [comment]
@mattharo : Hey, looks like the API issue has been fixed. It now returns the album relationship for a library artist :smiley:
