### ISSUE TITLE
Songs marked as Explicit are not played

### ISSUE THREAD

**Issue by jmahhh** [antrancs/maeve#52]
I noticed this with the "West Coast Classics" playlist: only non-E songs are played, and when it gets to an E-marked song it just stops.

**Comment by mradermaxlol** [comment]
Just tried playing some explicit songs in my library and it works just fine. "We Hate It When You Get What You Want" by Filter, for example.

**Comment by antrancs** [comment]
Hmm, interesting. I've tried playing the said playlist and it's playing fine for me. Is it still happening now?

**Comment by jmahhh** [comment]
Closing as I can't seem to replicate it myself!
