### ISSUE TITLE
Uncaught (in promise) DOMException when try to click play

### ISSUE THREAD

**Issue by egorzot** [antrancs/maeve#8]
When I trying to play in Chromium 71.0.3578.98 and Opera 57.0.3098.110 I've got [error](https://cloud.mail.ru/public/2Cx3/7kwK1BG4v) in  DevTools:

> Uncaught (in promise) DOMException

But Firefox 64.0 is ok. 
Is there a webkit bug? 🤔

**Comment by antrancs** [comment]
Yeah, I've tried with Chromium on Linux at work once and got a similar error. It's from MusicKitJS but I'm not sure why.

It works fine on Edge on Windows though (surprisingly) 😄.
For Linux: Chrome & Firefox. Windows: Edge & Chrome & Firefox. MacOS: Safari & Chrome & Firefox

**Comment by egorzot** [comment]
Yippee! Chromium 73.0.3683.75 - bug is gone!

**Comment by antrancs** [comment]
Great. Thanks for the update :grin:
